
defaults: &defaults
  fidobakku:
    initial_plan: premium
    demo_days: 42
    account_limits:
      basic:
        can_add_content: false
      premium:
        can_add_content: true

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
