
defaults: &defaults
  fidobakku:
    account_plan: basic
    account_expiry: 2013-03-01
    account_limits:
      basic:
        users: 5
        forms: 1
        sections: 3
        comps: 15
        evaluations: 1
      premium:
        users: 500
        forms: 1000
        sections: 3000
        comps: 15000
        evaluations: 1000

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
