
defaults: &defaults
  fidobakku:
    account_plan: premium
    demo_days: 42
    account_limits:
      basic:
        user_evaluations: false
        goals: false
        comments: false
      premium:
        user_evaluations: true
        goals: true
        comments: true

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
